<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TakeNote.Core\TakeNote.Core.csproj" />
		<ProjectReference Include="..\TakeNote.DataAccess\TakeNote.DataAccess.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
	</ItemGroup>

</Project>